### ISSUE TITLE
Exercise5: Unable to fetch databricks cluster

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Big-data-and-visualization#85] opened 2020-10-28 09:32 UTC
In Exercise 5 Task1, I am not to able to find the existing cluster from the dropdown. Even though cluster exists in the databricks workspace. Please find the screenshots below for reference.

![Screenshot (21)](https://user-images.githubusercontent.com/52440474/97417004-2fbbed80-192d-11eb-9ca7-44aa6d984eef.png)

![Screenshot (40)](https://user-images.githubusercontent.com/52440474/97418075-634b4780-192e-11eb-96ca-ef69efe9d6ae.png)

Thanks 
Tejaswini.

**Comment by DawnmarieDesJardins** [comment] 2020-10-28 15:19
@timahenning @joelhulen 
Unable to assign this issue to you at this time.  Please review and advise.

**Comment by joelhulen** [comment] 2020-10-28 16:42
@tejaswini972 I see that you are using a hosted environment. Can you please send me the environment details so I can log in and take a look? Send to (joel @ solliance.net)

**Comment by tejaswini972** [comment] 2020-10-28 16:51
Hi @joelhulen 
I don't have the environment right now!

**Comment by akn9050** [comment] 2020-11-02 11:53
Hi @joelhulen , did you get time to look at this, let me know if you need an hosted environment to check on this, i will get one for you.

Thanks

**Comment by joelhulen** [comment] 2020-11-02 12:05
@akn9050 if you can provide a hosted environment, that will help. I'll look at it today.

**Comment by akn9050** [comment] 2020-11-02 12:32
okay thanks, will share it on joel @ solliance.net

**Comment by joelhulen** [comment] 2020-11-02 13:35
@tejaswini972 I used the environment provided by @akn9050 just now and I was able to successfully select the Databricks cluster:

![image](https://user-images.githubusercontent.com/5950304/97873625-e6c9b780-1ce5-11eb-8d15-a3c705984b36.png)

Could you please confirm that for the **Access token** field, you entered the Azure Databricks access token you created in Steps 7-10? If so, please try creating a new access token.

![image](https://user-images.githubusercontent.com/5950304/97873896-3c9e5f80-1ce6-11eb-80fa-9703f6e30a8b.png)

Please note that you should paste the access token that is displayed only once when you create the token, and NOT the Token ID. If you are still having issues, I can share my environment if it's still up and running. In any case, I have confirmed that the steps still work and are accurate.

**Comment by joelhulen** [comment] 2020-11-03 12:06
Closing since I was unable to reproduce the issue in a fresh environment. If you still cannot get past this issue, please re-open.

**Closed by joelhulen** 2020-11-03 12:06 UTC
